# Generated by Django 5.1.2 on 2024-11-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='ahmed', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='earth', max_length=100),
        ),
        migrations.AddField(
            model_name='librarian',
            name='name',
            field=models.CharField(default='ali', max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='name',
            field=models.CharField(default='readbook', max_length=100),
        ),
    ]
